{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting fal\n",
      "  Using cached fal-0.2.15-py3-none-any.whl (52 kB)\n",
      "Collecting google-cloud-bigquery-storage<3.0.0,>=2.9.1\n",
      "  Using cached google_cloud_bigquery_storage-2.13.1-py2.py3-none-any.whl (180 kB)\n",
      "Collecting sqlalchemy-bigquery<2.0.0,>=1.2.2\n",
      "  Using cached sqlalchemy_bigquery-1.4.3-py2.py3-none-any.whl (32 kB)\n",
      "Collecting PyYAML<7.0,>=6.0\n",
      "  Using cached PyYAML-6.0-cp38-cp38-macosx_10_9_x86_64.whl (192 kB)\n",
      "Collecting snowflake-sqlalchemy<2.0.0,>=1.3.3\n",
      "  Using cached snowflake_sqlalchemy-1.3.3-py2.py3-none-any.whl (31 kB)\n",
      "Collecting agate-sql<0.6.0,>=0.5.8\n",
      "  Using cached agate_sql-0.5.8-py2.py3-none-any.whl (7.1 kB)\n",
      "Collecting deprecation<3.0.0,>=2.1.0\n",
      "  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)\n",
      "Collecting firebase-admin<6.0.0,>=5.1.0\n",
      "  Using cached firebase_admin-5.2.0-py3-none-any.whl (115 kB)\n",
      "Collecting pyarrow<6.0.0,>=5.0.0\n",
      "  Using cached pyarrow-5.0.0-cp38-cp38-macosx_10_13_x86_64.whl (17.6 MB)\n",
      "Collecting requests<3.0.0,>=2.27.1\n",
      "  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)\n",
      "Collecting pydantic<2.0.0,>=1.8.2\n",
      "  Using cached pydantic-1.9.0-cp38-cp38-macosx_10_9_x86_64.whl (2.9 MB)\n",
      "Collecting arrow<2.0.0,>=1.2.0\n",
      "  Using cached arrow-1.2.2-py3-none-any.whl (64 kB)\n",
      "Collecting google-cloud-bigquery<3.0.0,>=2.28.1\n",
      "  Using cached google_cloud_bigquery-2.34.3-py2.py3-none-any.whl (206 kB)\n",
      "Collecting sqlalchemy-redshift<0.9.0,>=0.8.9\n",
      "  Using cached sqlalchemy_redshift-0.8.9-py2.py3-none-any.whl (36 kB)\n",
      "Requirement already satisfied: pandas<2.0.0,>=1.3.4 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fal) (1.4.1)\n",
      "Collecting posthog<2.0.0,>=1.4.5\n",
      "  Using cached posthog-1.4.7-py2.py3-none-any.whl (22 kB)\n",
      "Collecting sqlalchemy>=1.0.8\n",
      "  Using cached SQLAlchemy-1.4.35-cp38-cp38-macosx_10_14_x86_64.whl (1.5 MB)\n",
      "Requirement already satisfied: agate>=1.5.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate-sql<0.6.0,>=0.5.8->fal) (1.6.1)\n",
      "Requirement already satisfied: leather>=0.3.2 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (0.3.3)\n",
      "Requirement already satisfied: Babel>=2.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (2.9.0)\n",
      "Requirement already satisfied: parsedatetime>=2.1 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (2.6)\n",
      "Requirement already satisfied: python-slugify>=1.2.1 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (4.0.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (1.15.0)\n",
      "Requirement already satisfied: pytimeparse>=1.1.5 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (1.1.8)\n",
      "Requirement already satisfied: isodate>=0.5.4 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (0.6.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from arrow<2.0.0,>=1.2.0->fal) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2015.7 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from Babel>=2.0->agate>=1.5.0->agate-sql<0.6.0,>=0.5.8->fal) (2020.5)\n",
      "Requirement already satisfied: packaging in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from deprecation<3.0.0,>=2.1.0->fal) (20.9)\n",
      "Collecting google-api-python-client>=1.7.8\n",
      "  Using cached google_api_python_client-2.46.0-py2.py3-none-any.whl (8.4 MB)\n",
      "Collecting google-cloud-storage>=1.37.1\n",
      "  Using cached google_cloud_storage-2.3.0-py2.py3-none-any.whl (107 kB)\n",
      "Collecting cachecontrol>=0.12.6\n",
      "  Using cached CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)\n",
      "Collecting google-cloud-firestore>=2.1.0\n",
      "  Using cached google_cloud_firestore-2.4.0-py2.py3-none-any.whl (243 kB)\n",
      "Requirement already satisfied: google-api-core[grpc]<3.0.0dev,>=1.22.1 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from firebase-admin<6.0.0,>=5.1.0->fal) (1.23.0)\n",
      "Requirement already satisfied: msgpack>=0.5.2 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from cachecontrol>=0.12.6->firebase-admin<6.0.0,>=5.1.0->fal) (1.0.2)\n",
      "Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (1.28.0)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (3.15.8)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (1.52.0)\n",
      "Requirement already satisfied: setuptools>=34.0.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (49.2.1)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.29.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (1.44.0)\n",
      "Collecting uritemplate<5,>=3.0.1\n",
      "  Using cached uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)\n",
      "Collecting google-auth-httplib2>=0.1.0\n",
      "  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)\n",
      "Collecting httplib2<1dev,>=0.15.0\n",
      "  Using cached httplib2-0.20.4-py3-none-any.whl (96 kB)\n",
      "Collecting google-api-python-client>=1.7.8\n",
      "  Using cached google_api_python_client-2.45.0-py2.py3-none-any.whl (8.4 MB)\n",
      "  Using cached google_api_python_client-2.44.0-py2.py3-none-any.whl (8.3 MB)\n",
      "  Using cached google_api_python_client-2.43.0-py2.py3-none-any.whl (8.3 MB)\n",
      "  Using cached google_api_python_client-2.42.0-py2.py3-none-any.whl (8.3 MB)\n",
      "  Using cached google_api_python_client-2.41.0-py2.py3-none-any.whl (8.3 MB)\n",
      "  Using cached google_api_python_client-2.40.0-py2.py3-none-any.whl (8.2 MB)\n",
      "  Using cached google_api_python_client-2.39.0-py2.py3-none-any.whl (8.2 MB)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (4.2.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (4.7.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (0.2.8)\n",
      "Collecting google-cloud-bigquery<3.0.0,>=2.28.1\n",
      "  Using cached google_cloud_bigquery-2.34.2-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.34.1-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.34.0-py2.py3-none-any.whl (206 kB)\n",
      "  Using cached google_cloud_bigquery-2.33.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.32.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.31.0-py2.py3-none-any.whl (205 kB)\n",
      "  Using cached google_cloud_bigquery-2.30.1-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.30.0-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.29.0-py2.py3-none-any.whl (203 kB)\n",
      "  Using cached google_cloud_bigquery-2.28.1-py2.py3-none-any.whl (202 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth-httplib2 to determine which version is compatible with other requirements. This could take a while.\n",
      "INFO: pip is looking at multiple versions of cachetools to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting cachetools<5.0,>=2.0.0\n",
      "  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)\n",
      "  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)\n",
      "  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)\n",
      "  Using cached cachetools-4.2.0-py3-none-any.whl (12 kB)\n",
      "  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)\n",
      "  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)\n",
      "  Using cached cachetools-4.0.0-py3-none-any.whl (10 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth-httplib2 to determine which version is compatible with other requirements. This could take a while.\n",
      "INFO: pip is looking at multiple versions of cachetools to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached cachetools-3.1.1-py2.py3-none-any.whl (11 kB)\n",
      "  Using cached cachetools-3.1.0-py2.py3-none-any.whl (12 kB)\n",
      "  Using cached cachetools-3.0.0-py2.py3-none-any.whl (12 kB)\n",
      "  Using cached cachetools-2.1.0-py2.py3-none-any.whl (12 kB)\n",
      "  Using cached cachetools-2.0.1-py2.py3-none-any.whl (11 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\n",
      "  Using cached cachetools-2.0.0-py2.py3-none-any.whl (11 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting google-auth<2.0dev,>=1.21.1\n",
      "  Using cached google_auth-1.35.0-py2.py3-none-any.whl (152 kB)\n",
      "  Using cached google_auth-1.34.0-py2.py3-none-any.whl (152 kB)\n",
      "  Using cached google_auth-1.33.1-py2.py3-none-any.whl (152 kB)\n",
      "  Using cached google_auth-1.33.0-py2.py3-none-any.whl (151 kB)\n",
      "  Using cached google_auth-1.32.1-py2.py3-none-any.whl (147 kB)\n",
      "  Using cached google_auth-1.32.0-py2.py3-none-any.whl (147 kB)\n",
      "  Using cached google_auth-1.31.0-py2.py3-none-any.whl (147 kB)\n",
      "INFO: pip is looking at multiple versions of google-auth to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached google_auth-1.30.2-py2.py3-none-any.whl (146 kB)\n",
      "  Using cached google_auth-1.30.1-py2.py3-none-any.whl (146 kB)\n",
      "  Using cached google_auth-1.30.0-py2.py3-none-any.whl (146 kB)\n",
      "  Using cached google_auth-1.29.0-py2.py3-none-any.whl (142 kB)\n",
      "  Using cached google_auth-1.28.1-py2.py3-none-any.whl (136 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\n",
      "  Using cached google_auth-1.28.0-py2.py3-none-any.whl (136 kB)\n",
      "  Using cached google_auth-1.27.1-py2.py3-none-any.whl (136 kB)\n",
      "  Using cached google_auth-1.27.0-py2.py3-none-any.whl (135 kB)\n",
      "  Using cached google_auth-1.26.1-py2.py3-none-any.whl (116 kB)\n",
      "  Using cached google_auth-1.26.0-py2.py3-none-any.whl (135 kB)\n",
      "  Using cached google_auth-1.25.0-py2.py3-none-any.whl (116 kB)\n",
      "  Using cached google_auth-1.24.0-py2.py3-none-any.whl (114 kB)\n",
      "  Using cached google_auth-1.23.0-py2.py3-none-any.whl (114 kB)\n",
      "  Using cached google_auth-1.22.1-py2.py3-none-any.whl (114 kB)\n",
      "  Using cached google_auth-1.22.0-py2.py3-none-any.whl (114 kB)\n",
      "Collecting aiohttp<4.0.0dev,>=3.6.2\n",
      "  Using cached aiohttp-3.8.1-cp38-cp38-macosx_10_9_x86_64.whl (574 kB)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/sung/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from aiohttp<4.0.0dev,>=3.6.2->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<3.0.0dev,>=1.22.1->firebase-admin<6.0.0,>=5.1.0->fal) (20.3.0)\n",
      "Collecting charset-normalizer<3.0,>=2.0\n",
      "  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)\n",
      "Collecting aiosignal>=1.1.2\n",
      "  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)\n",
      "Collecting async-timeout<5.0,>=4.0.0a3\n",
      "  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)\n",
      "Collecting frozenlist>=1.1.1\n",
      "  Using cached frozenlist-1.3.0-cp38-cp38-macosx_10_9_x86_64.whl (36 kB)\n",
      "Collecting yarl<2.0,>=1.0\n",
      "  Using cached yarl-1.7.2-cp38-cp38-macosx_10_9_x86_64.whl (121 kB)\n",
      "Collecting multidict<7.0,>=4.5\n",
      "  Using cached multidict-6.0.2-cp38-cp38-macosx_10_9_x86_64.whl (28 kB)\n",
      "INFO: pip is looking at multiple versions of frozenlist to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting frozenlist>=1.1.1\n",
      "  Using cached frozenlist-1.2.0-cp38-cp38-macosx_10_9_x86_64.whl (81 kB)\n",
      "  Using cached frozenlist-1.1.1-cp38-cp38-macosx_10_14_x86_64.whl (77 kB)\n",
      "INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting charset-normalizer<3.0,>=2.0\n",
      "  Using cached charset_normalizer-2.0.11-py3-none-any.whl (39 kB)\n",
      "  Using cached charset_normalizer-2.0.10-py3-none-any.whl (39 kB)\n",
      "INFO: pip is looking at multiple versions of frozenlist to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)\n",
      "  Using cached charset_normalizer-2.0.8-py3-none-any.whl (39 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\n",
      "  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)\n",
      "  Using cached charset_normalizer-2.0.6-py3-none-any.whl (37 kB)\n",
      "  Using cached charset_normalizer-2.0.5-py3-none-any.whl (37 kB)\n",
      "INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached charset_normalizer-2.0.4-py3-none-any.whl (36 kB)\n",
      "  Using cached charset_normalizer-2.0.3-py3-none-any.whl (35 kB)\n",
      "  Using cached charset_normalizer-2.0.2-py3-none-any.whl (35 kB)\n",
      "  Using cached charset_normalizer-2.0.1-py3-none-any.whl (35 kB)\n",
      "  Using cached charset_normalizer-2.0.0-py3-none-any.whl (35 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking\n",
      "^C\n",
      "\u001b[31mERROR: Operation cancelled by user\u001b[0m\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.\n",
      "You should consider upgrading via the '/Users/sung/.pyenv/versions/3.8.9/bin/python3.8 -m pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip3 install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'fal'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/hf/80s2zg792jv_n9rtdjt5rnkm0000gp/T/ipykernel_67321/249311312.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mfal\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mFalDbt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'fal'"
     ]
    }
   ],
   "source": [
    "from fal import FalDbt\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "f8c9727d417bd174c77210decdd1a2db8a2788f619ffa07b5ee607dc4b837a4b"
  },
  "kernelspec": {
   "display_name": "Python 3.8.9 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.9"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
